spring:
  profiles:
    active: h2
  weather:
    key: 508dff1acdabb7268e658e51914a2567
#    http://api.openweathermap.org/data/2.5/weather?q=Voronezh&appid=508dff1acdabb7268e658e51914a2567

---
#logging:
#  level:
#    root: debug
spring:
  config:
    activate:
      on-profile: h2, default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/party_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver